### ISSUE TITLE
Repeatedly building docker images on regular nodes

### ISSUE THREAD

**Issue by fishseabowl** [pyrsia/pyrsia#1231]
### Steps taken/Steps to reproduce

Steps:
1. Start nodeA (authorized node)
1. Add nodeA as authorized node 
    ```
    xuefeihan@xuefeih-mac pyrsia %./target/debug/pyrsia authorize --peer 12D3KooWFz7xbGccWoN4HsEY8yH8QUj6GSPqcJTimwayYjNykeEq
    ```
1. Start nodeB (regular node)
1. Build the docker image alpine:3.16.100 on nodeA
    ```
    xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia build docker --image alpine:3.16.100                            
    Build request successfully handled. Build with ID 6cae08b2-68d5-4446-809e-ed24517eb829 has been started.
    xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia inspect-log docker --image alpine:3.16.100                            
    [
      {
    "artifact_hash": "c766482b8dac037b60a137701852f3710c01f6ae2c21feeb3334aa77c559a108",
    "artifact_id": "b8297f68-34fa-4907-87c0-593ee5ce8662",
    "id": "8d0fc966-3156-4933-8838-62ba57fd99be",
    "node_id": "0373d0a1-8bb3-482d-8479-9bf6e4b4f207",
    "node_public_key": "6150ad04-0442-4bf0-8d27-206e49b2ab97",
    "num_artifacts": 3,
    "operation": "AddArtifact",
    "package_specific_artifact_id": "alpine:3.16.100",
    "package_specific_id": "alpine:3.16.100",
    "package_type": "Docker",
    "source_hash": "",
    "source_id": "0cab8763-272e-4b75-bc54-cc1b1b57e457",
    "timestamp": 1666299914
      },
      {
    "artifact_hash": "c766482b8dac037b60a137701852f3710c01f6ae2c21feeb3334aa77c559a108",
    "artifact_id": "0398cd6e-f2c3-4986-aa82-6f1860013821",
    "id": "43a0b721-033f-4a9a-8257-8c04bf0920e6",
    "node_id": "d545c1fe-d754-4b82-9840-7a5215aa1172",
    "node_public_key": "ba262fc1-a6d2-4384-959b-53aa15036535",
    "num_artifacts": 3,
    "operation": "AddArtifact",
    "package_specific_artifact_id": "alpine@sha256:c766482b8dac037b60a137701852f3710c01f6ae2c21feeb3334aa77c559a108",
    "package_specific_id": "alpine:3.16.100",
    "package_type": "Docker",
    "source_hash": "",
    "source_id": "0dbcc1a0-6510-4eae-ae1e-494498a9d641",
    "timestamp": 1666299914
      },
      {
    "artifact_hash": "b16e15764b8bc06c5c3f9f19bc8b99fa48e7894aa5a6ccdad65da49bbf564793",
    "artifact_id": "a70fab9f-5c15-4dd4-abcb-b6c7f35c7fb2",
    "id": "1270ba39-6062-49bc-9b65-3a12bac70e99",
    "node_id": "3873d32b-2239-4a37-a592-1847a9844593",
    "node_public_key": "00d0bacb-5bf6-42ed-8949-e17a25d63583",
    "num_artifacts": 3,
    "operation": "AddArtifact",
    "package_specific_artifact_id": "alpine@null",
    "package_specific_id": "alpine:3.16.100",
    "package_type": "Docker",
    "source_hash": "",
    "source_id": "789cbe9c-f85c-4dab-8823-6a4824a34f46",
    "timestamp": 1666299914
      }
   ]
   ```

1. Build the docker image alpine:3.16.100 on nodeA again, and an error is reported. `Now everything is normal.`

   ```
   xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia build docker --image alpine:3.16.100      
   Build request failed with error: HTTP status client error (400 Bad Request) for url (http://localhost:7889/build/docker)
   ```
1. config CLI to node B
1. Build the docker image alpine: 3.16.100 on nodeB again, which is successful. It should report errors. `Repeatedly building the docker image`
   ```
   xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia build docker --image alpine:3.16.100      
   Build request successfully handled. Build with ID 1 has been started.
   xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia build docker --image alpine:3.16.100      
   Build request successfully handled. Build with ID 2 has been started.
   ```

### Expected Behavior

The same docker image can only be built once on authorized nodes and regular nodes.

### Experienced Instance of the bug

rustc 1.63.0 (4b91a6ea7 2022-08-08)
Pyrsia 0.2.0(commit 77bfd6d5b64aa35e85bf3ac6e927673ef213a9ab)

**Comment by erwin1** [comment]
@fishseabowl I just tested this and it does work as expected. It was fixed in #1215 which was merged in https://github.com/pyrsia/pyrsia/commit/1f8da9cc16cda34271249c961bfde3538eabb1ee just after the commit you referred to.

maybe you can verify as well, so we can close this issue?

**Comment by fishseabowl** [comment]
@erwin1 The issue is still here.  Please double check it.

The steps to reproduce are as follows:
1. Run nodeA (authorized node)
```
  xuefeihan@xuefeih-mac nodeA % RUST_LOG=pyrsia=debug DEV_MODE=on \
  ./pyrsia_node --pipeline-service-endpoint http://localhost:8080 -p 7889 --listen-only --init-blockchain
```
2. Run build pipeline prototype
```
  xuefeihan@xuefeih-mac pyrsia_build_pipeline_prototype %RUST_LOG=debug cargo run
```
3. Add nodeA as authorized node
```
  xuefeihan@xuefeih-mac pyrsia %./target/debug/pyrsia authorize --peer 
  12D3KooWHjSr3b9Ucy9ZqHGq2T9r8oQmxL17DXu4uXqkc3pQJNAW
```
4. Run nodeB (regular node)
```
  xuefeihan@xuefeih-mac nodeB % RUST_LOG=pyrsia=debug DEV_MODE=on \
  ./pyrsia_node --peer /ip4/127.0.0.1/tcp/52309/p2p/12D3KooWHjSr3b9Ucy9ZqHGq2T9r8oQmxL17DXu4uXqkc3pQJNAW
```
5. Build the docker image alpine:3.16.1 on nodeA(`config port to 7889`)
```
  xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia build docker --image alpine:3.16.1
  Build request successfully handled. Build with ID 189a0fbe-b9dc-4b02-8304-8651cbfb69b5 has been started.
```
6. Build the docker image alpine:3.16.1 on nodeA again, and an error is reported. `Now everything is normal`.
```
  xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia build docker --image alpine:3.16.1
  Build request failed with error: HTTP status client error (400 Bad Request) for url (http://localhost:7889/build/docker)
```
7. Config Pyrsia CLI to node B(`config port to 7888`)
8. Build the docker image alpine: 3.16.1 on nodeB, which is successful. `It should report an error like Step 6`. 
```
 xuefeihan@xuefeih-mac pyrsia % ./target/debug/pyrsia build docker --image alpine:3.16.1
 Build request successfully handled. Build with ID 1 has been started.
```

**Comment by erwin1** [comment]
Double checked, and I really can't reproduce (on commit f68dc5d7b5f1cc8f93fd2097533b5ec7b7e705f3). My output at step 8 is:
```
./pyrsia build docker --image alpine:3.16.1
Build request failed with error: HTTP status client error (400 Bad Request) for url (http://localhost:7888/build/docker)
```

while I see this in the node B logs
```
DEBUG pyrsia::docker::error_util           > Rejection: Rejection(RegistryError { code: BadRequest("Failed to start a build: ArtifactAlreadyExists { package_type: Docker, package_specific_id: \"alpine:3.16.1\" }") })
```

The most obvious reason this would happen is that node B didn't receive the blocks for the publication of the artifact you're trying to build. Is there anything in your node B logs that can help?
Also, before doing step 8, try to run:
```
./pyrsia inspect-log docker --image alpine:3.16.1
```
to check if the artifact is present in the transparency log.

**Comment by fishseabowl** [comment]
Closed due to fix
